# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerFrame(object):
    def setupUi(self, ServerFrame):
        ServerFrame.setObjectName("ServerFrame")
        ServerFrame.resize(531, 367)
        self.gridLayout = QtWidgets.QGridLayout(ServerFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.mainScrollArea = QtWidgets.QScrollArea(ServerFrame)
        self.mainScrollArea.setWidgetResizable(True)
        self.mainScrollArea.setObjectName("mainScrollArea")
        self.mainWorking = QtWidgets.QWidget()
        self.mainWorking.setGeometry(QtCore.QRect(0, 0, 511, 347))
        self.mainWorking.setObjectName("mainWorking")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainWorking)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblLogs = QtWidgets.QLabel(self.mainWorking)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblLogs.setFont(font)
        self.lblLogs.setObjectName("lblLogs")
        self.gridLayout_2.addWidget(self.lblLogs, 0, 0, 1, 1)
        self.lblOnlineUser = QtWidgets.QLabel(self.mainWorking)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblOnlineUser.setFont(font)
        self.lblOnlineUser.setObjectName("lblOnlineUser")
        self.gridLayout_2.addWidget(self.lblOnlineUser, 0, 2, 1, 1)
        self.onlUserTextArea = QtWidgets.QPlainTextEdit(self.mainWorking)
        self.onlUserTextArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onlUserTextArea.sizePolicy().hasHeightForWidth())
        self.onlUserTextArea.setSizePolicy(sizePolicy)
        self.onlUserTextArea.setReadOnly(True)
        self.onlUserTextArea.setObjectName("onlUserTextArea")
        self.gridLayout_2.addWidget(self.onlUserTextArea, 1, 2, 1, 1)
        self.logsTextArea = QtWidgets.QPlainTextEdit(self.mainWorking)
        self.logsTextArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logsTextArea.sizePolicy().hasHeightForWidth())
        self.logsTextArea.setSizePolicy(sizePolicy)
        self.logsTextArea.setReadOnly(True)
        self.logsTextArea.setObjectName("logsTextArea")
        self.gridLayout_2.addWidget(self.logsTextArea, 1, 0, 1, 2)
        self.btnKick = QtWidgets.QPushButton(self.mainWorking)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnKick.setFont(font)
        self.btnKick.setObjectName("btnKick")
        self.gridLayout_2.addWidget(self.btnKick, 2, 0, 1, 3)
        self.mainScrollArea.setWidget(self.mainWorking)
        self.gridLayout.addWidget(self.mainScrollArea, 0, 0, 1, 1)

        self.retranslateUi(ServerFrame)
        QtCore.QMetaObject.connectSlotsByName(ServerFrame)

    def retranslateUi(self, ServerFrame):
        _translate = QtCore.QCoreApplication.translate
        ServerFrame.setWindowTitle(_translate("ServerFrame", "Weather NetWorking"))
        self.lblLogs.setText(_translate("ServerFrame", "Logs"))
        self.lblOnlineUser.setText(_translate("ServerFrame", "Online User"))
        self.btnKick.setText(_translate("ServerFrame", "Kick that user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ServerFrame = QtWidgets.QFrame()
    ui = Ui_ServerFrame()
    ui.setupUi(ServerFrame)
    ServerFrame.show()
    sys.exit(app.exec_())
